name: Deploy Cloudflare Worker
on:
  push:
    branches: [ "main" ]
    paths:
      - backend/**
      - .github/workflows/deploy-backend.yaml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: '4.131.0'
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: "backend"
